# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
  pull_request:

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: tsc compile
        uses: iCrawl/action-tsc@v1
        with:
          project: subdirectorywith_tsconfig
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
